export const reducerCases={
    SET_USER_INFO:"SET_USER_INFO",
    SET_NEW_USER:"SET_NEW_USER",
    SET_ALL_CONTACTS_PAGE:"SET_ALL_CONTACTS_PAGE",
    CHANGE_CURRENT_CHAt_USER:"CHANGE_CURRENT_CHAt_USER",
    SET_MESSAGES:"SET_MESSAGES",
    SET_SOCKET:"SET_SOCKET",
    ADD_MESSAGES:"ADD_MESSAGES",
}